In [1]:
import pandas as pd

#### to run on full training set, load train.csv instead of train_month_slice.parquet, the rest of the code can stay as is

In [2]:
train = pd.read_parquet('../data/sample/train_month_slice.parquet')
train.head()

,id,date,store_nbr,item_nbr,unit_sales,onpromotion,year,month,day,dayofweek
120761105,120761105,2017-07-02,1,103665,1.0,0,2017,7,2,6
120761106,120761106,2017-07-02,1,105575,6.0,0,2017,7,2,6
120761107,120761107,2017-07-02,1,105857,1.0,0,2017,7,2,6
120761108,120761108,2017-07-02,1,106716,2.0,0,2017,7,2,6
120761109,120761109,2017-07-02,1,108634,5.0,0,2017,7,2,6

In [3]:
print(train.shape)

(4735935, 10)

## Merge transactions

In [4]:
transactions = pd.read_csv('../data/raw/favorita-grocery-sales-forecasting/transactions.csv')
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [5]:
print(transactions.shape)

(83488, 3)

In [6]:
# date is of different types in the two tables
merge_trans = train.astype({'date': 'str'}).merge(transactions, how='left', on=['date', 'store_nbr'])
merge_trans

,id,date,store_nbr,item_nbr,unit_sales,onpromotion,year,month,day,dayofweek,transactions
0,120761105,2017-07-02,1,103665,1.0,0,2017,7,2,6,542
1,120761106,2017-07-02,1,105575,6.0,0,2017,7,2,6,542
2,120761107,2017-07-02,1,105857,1.0,0,2017,7,2,6,542
3,120761108,2017-07-02,1,106716,2.0,0,2017,7,2,6,542
4,120761109,2017-07-02,1,108634,5.0,0,2017,7,2,6,542
...,...,...,...,...,...,...,...,...,...,...,...
4735930,125497035,2017-08-15,54,2089339,4.0,0,2017,8,15,1,802
4735931,125497036,2017-08-15,54,2106464,1.0,1,2017,8,15,1,802
4735932,125497037,2017-08-15,54,2110456,192.0,0,2017,8,15,1,802
4735933,125497038,2017-08-15,54,2113914,198.0,1,2017,8,15,1,802
4735934,125497039,2017-08-15,54,2116416,2.0,0,2017,8,15,1,802

## Merge items

In [7]:
items = pd.read_csv('../data/raw/favorita-grocery-sales-forecasting/items.csv')
items.head()

   item_nbr        family  class  perishable
0     96995     GROCERY I   1093           0
1     99197     GROCERY I   1067           0
2    103501      CLEANING   3008           0
3    103520     GROCERY I   1028           0
4    103665  BREAD/BAKERY   2712           1

In [8]:
print(items.shape)

(4100, 4)

In [9]:
merge_trans_items = merge_trans.merge(items, how='left', on='item_nbr')
merge_trans_items

,id,date,store_nbr,item_nbr,unit_sales,onpromotion,year,month,day,dayofweek,transactions,family,class,perishable
0,120761105,2017-07-02,1,103665,1.0,0,2017,7,2,6,542,BREAD/BAKERY,2712,1
1,120761106,2017-07-02,1,105575,6.0,0,2017,7,2,6,542,GROCERY I,1045,0
2,120761107,2017-07-02,1,105857,1.0,0,2017,7,2,6,542,GROCERY I,1092,0
3,120761108,2017-07-02,1,106716,2.0,0,2017,7,2,6,542,GROCERY I,1032,0
4,120761109,2017-07-02,1,108634,5.0,0,2017,7,2,6,542,GROCERY I,1075,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4735930,125497035,2017-08-15,54,2089339,4.0,0,2017,8,15,1,802,GROCERY I,1006,0
4735931,125497036,2017-08-15,54,2106464,1.0,1,2017,8,15,1,802,BEVERAGES,1148,0
4735932,125497037,2017-08-15,54,2110456,192.0,0,2017,8,15,1,802,BEVERAGES,1120,0
4735933,125497038,2017-08-15,54,2113914,198.0,1,2017,8,15,1,802,CLEANING,3040,0
4735934,125497039,2017-08-15,54,2116416,2.0,0,2017,8,15,1,802,GROCERY I,1060,0